part6/part6/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pets/', include('pets.urls', namespace='pets')),
    url(r'^$', RedirectView.as_view(pattern_name='pets:login', permanent=False)),
]

part6/pets/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^home/$', pets_home, name='home'),
    url(r'^home/index/$', pets_index, name='index'),
    url(r'^home/user_info/$', user_info, name='user_info'),
    url(r'^home/create_user/$', create_user, name='create_user'),
    url(r'^home/create_owner/$', create_owner, name='create_owner'),
    url(r'^home/create_pet/$', create_pet, name='create_pet'),
]

part6/pets/models.py
from __future__ import unicode_literals

from django.db import models
from django.core import validators


class Owner(models.Model):
    """
    A class representing the owner of a pet
    add a to string
    """
    PET_TYPE_CHOICES = {
        ("None", "None"),
        ("Cat", "Cat"),
        ("Dog", "Dog"),
        ("Rabbit", "Rabbit"),
        ("Hamster", "Hamster"),
        ("Gerbil", "Gerbil"),
        ("Bird", "Bird"),
    }

    first_name = models.CharField(
            'First Name',
            max_length=50,
            default=' ',
            validators=[
                validators.RegexValidator(
                        r'^[A-Z][a-zA-Z]*[^_]$',
                        'Name invalid. This value must start with an '
                        'uppercase letter and only contain letters.'
                )
            ]
    )
    last_name = models.CharField(
            'Last Name',
            max_length=50,
            default=' ',
            validators=[
                validators.RegexValidator(
                        r'^[A-Z][a-zA-Z]*[^_]$',
                        'Name invalid. This value must start with an '
                        'uppercase letter and only contain letters.'
                )
            ]
    )
    dob = models.DateField('Date of Birth')
    favorite_pet_type = models.CharField('Favorite Type of Pet', max_length=50, choices=PET_TYPE_CHOICES, blank=True)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Pet(models.Model):
    """
    A class representing an animal that is a pet
    """
    PET_TYPE_CHOICES = {
        ("Cat", "Cat"),
        ("Dog", "Dog"),
        ("Rabbit", "Rabbit"),
        ("Hamster", "Hamster"),
        ("Gerbil", "Gerbil"),
        ("Bird", "Bird"),
    }

    name = models.CharField(
            'Name',
            max_length=50,
            default=' ',
            validators=[
                validators.RegexValidator(
                        r'^[A-Z][a-zA-Z]*[^_]$',
                        'Name invalid. This value must start with an '
                        'uppercase letter and only contain letters.'
                )
            ]
    )
    type = models.CharField('Type', max_length=30, choices=PET_TYPE_CHOICES)
    owner = models.ForeignKey('Owner', Owner)
    age = models.PositiveIntegerField(
            'Age',
            default=0,
            validators=[
                validators.MinValueValidator(
                        1,
                        'Age invalid. Enter an age greater than one.'
                )

            ]
    )

part6/pets/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from .models import Pet, Owner


class PetForm(forms.ModelForm):
    """
    Form for creating a pet object
    """

    class Meta:
        model = Pet
        fields = ['name', 'type', 'owner', 'age']


class OwnerForm(forms.ModelForm):
    """
    Form for creating an owner object
    """

    class Meta:
        model = Owner
        fields = ['first_name', 'last_name', 'dob', 'favorite_pet_type']


class UserForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, with a first_name, last_name,
    username, email, and password.
    Most of this form is copied from the built in UserCreation form found in
    django.contrib.auth.forms.UserCreationForm
    What is added is first_name, last_name, and email.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }

    password1 = forms.CharField(label=_("Password"),
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
                                widget=forms.PasswordInput,
                                help_text=_("Enter the same password as before, for verification."))

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name")

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
            )
        self.instance.username = self.cleaned_data.get('username')
        password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    """
    Form for getting fields necessary for a login
    """
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput())

part6/pets/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect

from .models import Pet, Owner
from .forms import PetForm, OwnerForm, LoginForm, UserForm


@login_required
def pets_index(request):
    """
    Renders a page showing a list of owners and their pets
    :param request:
    :return pets index page
    """
    context = dict()
    context['owners'] = Owner.objects.all()
    context['pets'] = Pet.objects.all()
    return render(request, 'pets/index.html', context)


@login_required
def pets_home(request):
    """
    Renders the homepage of links to the rest of the pages
    :param request:
    :return: homepage
    """
    return render(request, 'pets/home.html')


@login_required
def create_pet(request):
    """
    Renders a page that displays a form to create and save a new pet object
    :param request:
    :return:
    """
    if request.method == 'GET':
        context = dict()
        context['form'] = PetForm()
        return render(request, 'pets/create_pet.html', context)
    elif request.method == 'POST':
        form = PetForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pets:home')
        else:
            context = dict()
            context['form'] = form
            return render(request, 'pets/create_pet.html', context)


@login_required
def create_owner(request):
    """
    Renders a page that displays a form to create and save a new owner object
    :param request:
    :return:
    """
    if request.method == 'GET':
        context = dict()
        context['form'] = OwnerForm()
        return render(request, 'pets/create_owner.html', context)
    elif request.method == 'POST':
        form = OwnerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pets:home')
        else:
            context = dict()
            context['form'] = form
            return render(request, 'pets/create_owner.html', context)


def create_user(request):
    """
    Renders a page that displays a form to create a user using the built
    :param request:
    :return:
    """
    if request.method == 'GET':
        context = dict()
        context['form'] = UserForm()
        return render(request, 'pets/create_user.html', context)
    elif request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pets:login')
        else:
            context = dict()
            context['form'] = form
            return render(request, 'pets/create_user.html', context)


@login_required
def user_info(request):
    """
    Renders a page that shows the information of the currently logged in user
    :param request:
    :return:
    """
    return render(request, 'pets/user_info.html')


def user_login(request):
    """
    Login page to login and authenticate users
    :param request:
    :return:
    """
    if request.method == 'GET':
        context = dict()
        context['form'] = LoginForm()
        return render(request, 'pets/login.html', context)
    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('pets:home')
                else:
                    context = dict()
                    return render(request, 'pets/login.html', context)
            else:
                context = dict()
                context['form'] = form
                return render(request, 'pets/login.html', context)
        else:
            context = dict()
            context['form'] = form
            return render(request, 'pets/login.html', context)


def user_logout(request):
    """
    Logout method that returns the user to the login page
    :param request:
    :return:
    """
    logout(request)
    return redirect('pets:login')

part6/pets/templates/pets/create_owner.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Owner</title>
</head>
<body>
<h3>Create a New Owner</h3>
<form method="post" action='{% url 'pets:create_owner' %}' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
    <button type="button" onclick="location.href='{% url 'pets:home' %}'">Back</button>
</form>
</body>
</html>

part6/pets/templates/pets/create_pet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Pet</title>
</head>
<body>
<h3>Create a New Pet</h3>
{# List out all the errors the form has at the very top of the page #}
{# This if statement checks if any errors exist in the form #}
{% if form.errors %}
    {# Iterate through all the fields in the form #}
    {% for field in form %}
        {# Iterate through all the errors of each field #}
        <div>
            <ul>
                {% for error in field.errors %}
                    {# Display the error for the user to see #}
                    <li><strong>{{ field.label }}: {{ error|escape }}</strong></li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
    {# Iterate through all non_field_errors if they exist #}
    {# non_field_errors are errors that don't pertain to a specific field #}
    <div>
        <ul>
            {% for error in form.non_field_errors %}
                <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
<form method="post" action='{% url 'pets:create_pet' %}' enctype="multipart/form-data">
    {% csrf_token %}
    {# Get the errors for each individual field and display them next to each field #}
    {# Check if a the specific field has any errors #}
    {% if form.name.errors %}
        <div>
            <ul>
                {# Iterate through all the errors of the name field #}
                {% for error in form.name.errors %}
                    {# Display the error for the user to see #}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <p>Name: {{ form.name }}</p>
    {% if form.type.errors %}
        <div>
            <ul>
                {% for error in form.type.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <p>Type: {{ form.type }}</p>
    {% if form.age.errors %}
        <div>
            <ul>
                {% for error in form.age.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <p>Age: {{ form.age }}</p>
    {% if form.owner.errors %}
        <div>
            <ul>
                {% for error in form.owner.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <p>Owner: {{ form.owner }}</p>
    <button type="submit">Submit</button>
    <button type="button" onclick="location.href='{% url 'pets:home' %}'">Back</button>
</form>
</body>
</html>

part6/pets/templates/pets/create_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create User</title>
</head>
<body>
<h3>Create a New User</h3>
<form method="post" action='{% url 'pets:create_user' %}' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
    <button type="button" onclick="location.href='{% url 'pets:login' %}'">Back</button>
</form>
</body>
</html>

part6/pets/templates/pets/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
<h3>Homepage For Owners and Pets</h3>
<p><a href='{% url 'pets:user_info' %}'>My User Info</a></p>
<p><a href='{% url 'pets:index' %}'>View all pets and owners</a></p>
<p><a href='{% url 'pets:create_owner' %}'>Create a new owner</a></p>
<p><a href='{% url 'pets:create_pet' %}'>Create a new pet</a></p>
<p><a href='{% url 'pets:logout' %}'>Logout</a></p>
</body>
</html>

part6/pets/templates/pets/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
<h3>A List of Owners and Their Pets</h3>
{% for owner in owners %}
    <p>{{ owner.first_name }} {{ owner.last_name }}</p>
    <ul>
        {% for pet in pets %}
            {% if pet.owner == owner %}
                <li>{{ pet.name }}</li>
            {% endif %}
        {% endfor %}
    </ul>
{% endfor %}
<button type="button" onclick="location.href='{% url 'pets:home' %}'">Back</button>
</body>
</html>

part6/pets/templates/pets/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<h3>Login</h3>
<form method="post" action="{% url 'pets:login' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>
    <button type="submit">Login</button>
</form>
<p>Don't have an account? Register Now!</p>
<button type="button" onclick="location.href='{% url 'pets:create_user' %}'">Register</button>
</body>
</html>

part6/pets/templates/pets/user_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My User Info</title>
</head>
<body>
<h3>My User Info</h3>
<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>First Name: {{ user.first_name }}</p>
<p>Last Name: {{ user.last_name }}</p>
<button type="button" onclick="location.href='{% url 'pets:home' %}'">Back</button>
</body>
</html>